# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inStock', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('picture', models.URLField(default='')),
                ('year', models.IntegerField(default=0)),
                ('color', models.CharField(default='', max_length=10)),
                ('type_wine', models.CharField(default='', max_length=40)),
                ('city', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('company', models.CharField(default='', max_length=50)),
                ('about', models.TextField(default='')),
                ('tags', models.TextField(default='')),
            ],
        ),
    ]
